# Generated by Django 3.1.3 on 2020-11-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0004_palestrante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palestrante',
            old_name='cdf',
            new_name='cpf',
        ),
        migrations.AddField(
            model_name='evento',
            name='curso_organizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.curso'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(default='2020-11-03'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(default='2020-11-03'),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.funcionario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='palestrantes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.palestrante'),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='telefone',
            field=models.CharField(max_length=9),
        ),
    ]
