# Generated by Django 3.1.3 on 2020-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0009_auto_20201103_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.CharField(default='teste', max_length=200),
        ),
    ]
